Add loop_index
networked-aframe/minijanus.js pull request #2
Opened 2023-06-07 15:48 UTC by hjopel

Allows minijanus to specify a loop index as documented in https://github.com/meetecho/janus-gateway/blob/master/conf/janus.jcfg.sample.in#L108

2023-06-12 08:26 UTC, vincentfretin requested changes

2023-06-12 08:26 UTC, vincentfretin commented on minijanus.js
> +  var payload = { plugin: plugin, loop_index: loop_index, "force-bundle": true, "force-rtcp-mux": true };
Is this working correctly on janus side if we give `loop_index: undefined`?
It's probably better to not include the key at all in the payload if it's undefined, less bytes to send :)
Do this:
```
if (loop_index) {
  payload.loop_index = loop_index;
}
```

2023-06-13 08:06 UTC, vincentfretin requested changes
At first I thought the key would be in the json, but actually no, when you serialize an object that have a key with undefined value, the key is discarded:
```js
JSON.stringify({"force-rtcp-mux": true, loop_index: undefined})
'{"force-rtcp-mux":true}'
```

so your previous version was good.
The new version with the condition is actually wrong, if loop_index is 0, it won't set it.
Can you please revert back to the previous version and I'll merge, I'm so sorry.

2023-06-13 08:50 UTC, hjopel commented
> At first I thought the key would be in the json, but actually no, when you serialize an object that have a key with undefined value, the key is discarded:
> 
> ```js
> JSON.stringify({"force-rtcp-mux": true, loop_index: undefined})
> '{"force-rtcp-mux":true}'
> ```
> 
> so your previous version was good. The new version with the condition is actually wrong, if loop_index is 0, it won't set it. Can you please revert back to the previous version and I'll merge, I'm so sorry.

that's true, I should've also caught that 🥲

2023-06-13 10:23 UTC, vincentfretin approved these changes
Thank you.

2023-06-13 10:27 UTC, merged